apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: service1

configMapGenerator:
    - name: config-env-name
      literals:
        - cluster_name=service1-arik

transformers:
  - |-
    apiVersion: builtin
    kind: LabelTransformer
    metadata:
      name: commonLabelsTransformer
    labels:
      app.kubernetes.io/cluster_name: service1-arik

    fieldSpecs:
    - path: metadata/labels
      create: true
    - path: spec/template/metadata/labels
      create: true
      kind: Deployment

resources:
- ./mongo
- ./service1