apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    App: mongodb
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      App: mongodb
  strategy: {}
  template:
    metadata:
      name: mongodb
      labels:
        App: mongodb
    spec:
      containers:
        - image: public.ecr.aws/docker/library/mongo:8.0.0-rc20
          imagePullPolicy: "Always"
          name: mongodb
          ports:
            - containerPort: 27017
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}

