version: "2"
services:
  webserver:
    restart: unless-stopped
    privileged: true
    image: 851725552187.dkr.ecr.eu-west-1.amazonaws.com/service1_arik:0.0.12
    depends_on:
      - mongodb
    ports:
        - "3000:3000"
  mongodb:
    image: public.ecr.aws/docker/library/mongo:8.0.0-rc20
    ports:
        - "27017:27017"
