version: "2"
services:
  webserver:
    restart: unless-stopped
    privileged: true
    image: arik-service1/service2
    depends_on:
      - mongodb
    ports:
        - "3000:3000"
  mongodb:
    image: 851725552187.dkr.ecr.eu-west-1.amazonaws.com/service1_arik:0.0.10
    ports:
        - "27017:27017"
